sudo: required
language: generic
env:
  global:
  - PROJECT_NAME=scar
matrix:
  include:
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=stable
    addons:
      apt:
        packages: &1
        - gcc-arm-linux-gnueabihf
        - libc6-armhf-cross
        - libc6-dev-armhf-cross
        - qemu-user
  - os: osx
    env: TARGET=i686-apple-darwin CHANNEL=stable
  - os: linux
    env: TARGET=i686-unknown-linux-gnu CHANNEL=stable
    addons:
      apt:
        packages: &2
        - gcc-multilib
  - os: osx
    env: TARGET=x86_64-apple-darwin CHANNEL=stable
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu CHANNEL=stable
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl CHANNEL=stable
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=beta
    addons:
      apt:
        packages: *1
  - os: osx
    env: TARGET=i686-apple-darwin CHANNEL=beta
  - os: linux
    env: TARGET=i686-unknown-linux-gnu CHANNEL=beta
    addons:
      apt:
        packages: *2
  - os: osx
    env: TARGET=x86_64-apple-darwin CHANNEL=beta
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu CHANNEL=beta
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl CHANNEL=beta
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=nightly
    addons:
      apt:
        packages: *1
  - os: osx
    env: TARGET=i686-apple-darwin CHANNEL=nightly
  - os: linux
    env: TARGET=i686-unknown-linux-gnu CHANNEL=nightly
    addons:
      apt:
        packages: *2
  - os: osx
    env: TARGET=x86_64-apple-darwin CHANNEL=nightly
  - os: linux
    env: TARGET=x86_64-unknown-linux-gnu CHANNEL=nightly
  - os: linux
    env: TARGET=x86_64-unknown-linux-musl CHANNEL=nightly
  allow_failures:
  - os: linux
    env: TARGET=arm-unknown-linux-gnueabihf CHANNEL=stable
install:
- export PATH="$PATH:~/multirust/bin"
- bash ci/install.sh
script:
- bash ci/script.sh
before_deploy:
- bash ci/before_deploy.sh
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
notifications:
  email:
    on_success: never
deploy:
  provider: releases
  api_key:
    secure: PCU9m3cL9Gzmw96CxqOChKJ1XnxzqyzDN1vkFPzXvZCWyB5Uz1VWISei17dWZq7HYIwHbA734/xodjMXiM953GPwb7uu7AeyiGGvtjm2iyMNLbMDgkrsFT135QRh1MHzOHMrI31iN3lDH+xLUDIMd9PYGgUyw1E0FZ7nwb0E/tKeW2/gFNLoAkQ6hEGKYa4geatgCnsHZuyltyzAIEWDmlRqGaZD/uG1xJzijSOcKUZjte50r2Zm2tzL41eNyAkc6Q8L730Cu5n6obEwkV5sxW4PHgm69xvHmKMh6dZlhWH/S8s325DJ/c2yF0pzMwhHT/Bt901kXI7JPje/lMBeUzS6rOGDCoqef4539/l1rWLyKfpU7u7N08vyj24UKkHkhVdnUDJgDkxB3L6BiqPe9K3i6fWKYyFMn5VazAuHRvTl8Q+vXHtlYg+C5YrxIkaRXK0UeImGwA83L4664Q7numl5bms+ZFAQ3SY9rCbfXaQrKFIO592EFzdouDroBA7zcpBtXZCDodbRbxP8jDCMXEgB0qD+iCZET7VqELV8Raipq5o9LWKTYBKiqLAxsTVoNHtJUJIaogZtJwBu0MkF1JW/MW0oOMQ9leYII1sZJ0KyOkbGQyJqJ0aD4Gc4g5FKR7CXvxqIZPEH5aYz02tDvwH6OHP6XXZocqUpX7mDseQ=
  file: "${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.tar.gz"
  on:
    repo: ProjectParanoia/scar
